/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:8d75161d-e58c-46b5-b5a3-c8884788add8",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_L5LSC0YF3",
    "aws_user_pools_web_client_id": "2343n6tbjn6kaqvju84dn1s727",
    "oauth": {}
};


export default awsmobile;
